=== Acidburn0zzz/definitions/nxdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $LastChangedDate$
# $LastChangedBy$
# $LastChangedRevision$
# $HeadURL$
########### SVN repository information ###################
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://definition.nexusformat.org/nxdl/3.1"
	xmlns:nx="http://definition.nexusformat.org/nxdl/3.1" 
	version="$Id$"
	elementFormDefault="qualified">

	<xs:annotation>
		<xs:documentation>
			# NeXus - Neutron and X-ray Common Data Format
			# 
			# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
			# 
			# This library is free software; you can redistribute it and/or
			# modify it under the terms of the GNU Lesser General Public
			# License as published by the Free Software Foundation; either
			# version 2 of the License, or (at your option) any later version.
			#
			# This library is distributed in the hope that it will be useful,
			# but WITHOUT ANY WARRANTY; without even the implied warranty of
			# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
			# Lesser General Public License for more details.
			#
			# You should have received a copy of the GNU Lesser General Public
			# License along with this library; if not, write to the Free Software
			# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
			#
			# For further information, see http://www.nexusformat.org
		</xs:documentation>
	</xs:annotation>
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	
	<xs:include schemaLocation="nxdlTypes.xsd">
		<xs:annotation>
			<xs:documentation>
				Definitions of the basic data types and unit types 
				allowed in NXDL instance files.
			</xs:documentation>
		</xs:annotation>
	</xs:include>
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	
	<!-- define the document root element -->
	<xs:element name="definition" type="nx:definitionType" />
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="definitionType">
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded" />
		<xs:attribute name="name" use="required" />
		<xs:attribute name="type" use="required" type="nx:definitionTypeAttr" />
		<xs:attribute name="extends" use="required" />
		<xs:attribute name="svnid" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="attributeType">
		<xs:annotation>
			<xs:documentation>
				A new element may expect or require some attributes.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" />
			<xs:element name="enumeration" type="nx:enumerationType"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>The field can have an enumeration of values</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" />
		<xs:attribute name="type" type="nx:primitiveType" default="NX_CHAR"/>
	</xs:complexType>

	<xs:simpleType name="definitionTypeAttr">
		<xs:restriction base="xs:string">
			<xs:enumeration value="group" />
			<xs:enumeration value="definition" />
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="groupGroup">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="attribute" type="nx:attributeType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="group" type="nx:groupType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="field" type="nx:fieldType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="basicComponent">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" use="required" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:simpleType name="docType">
		<xs:annotation>
			<xs:documentation>
				This is the basic definition of a new type.
				Components must derive from an existing type 
				and optionally provide documentation.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="groupType">
		<xs:annotation>
			<xs:documentation>
				A group element will be used to refer to an existing NX object or locally-defined component.
			</xs:documentation>
		</xs:annotation>
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="NX.+"></xs:pattern>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="minOccurs" use="optional" default="0" type="xs:nonNegativeInteger"/>
		<xs:attribute name="maxOccurs" use="optional"  default="unbounded"/>
		<xs:attribute name="name" use="optional" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="dimsType">
		<!--
			Here is a model:
			<field name="data">
			    <dimensions size="3"/>
			    ...
			</field><field name="time-of-flight">
				<dimensions size="1">
					<dim index="1" ref="data" refindex="3" incr="1"/>
				</dimensions>
				...
			</field>
			
			In old terms this would make data[i,j,k] and time-of-flight[k+1]. 
			We need to get to the stage where people
			don't need to read a manual to understand an existing NXDL.
		-->
		<xs:annotation>
			<xs:documentation>dimensions of a data element in a NeXus file</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="dim" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:attribute name="index" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Number indicating which subscript is being referenced, 
								ranging from 1 up to RANK (rank of the data structure).  For example, 
								given an array A[i,j,k], index="1" would refer to the "i" subscript.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="ref" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Name of the data structure being referenced indirectly.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="refindex" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Index within the data structure being referenced indirectly.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="incr" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>What is this?</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="size" type="nx:NX_CHAR">
			<xs:annotation>
				<xs:documentation>Rank (number of dimensions) of the data structure.  
					For example: a[5] has size="1" while b[8,5,6,4] has size="4".  
					See http://en.wikipedia.org/wiki/Rank_(computer_programming) 
					for more details.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:annotation>
				<xs:documentation>A field element will be used to declare a new element in the component being defined.</xs:documentation>
			</xs:annotation>
			<xs:extension base="nx:basicComponent">
				<xs:sequence>
					<xs:element name="dimensions" type="nx:dimsType"
						minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>dimensions of a data element in a NeXus file</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="attribute" type="nx:attributeType"
						minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>attributes of field</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="enumeration" type="nx:enumerationType"
						minOccurs="0">
						<xs:annotation>
							<xs:documentation>The field can have an enumeration of values</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="units" type="nx:anyUnitsAttr">
					<xs:annotation>
						<xs:documentation>
							String describing the engineering units.
							The string should be appropriate for the value
							and should conform to the NeXus rules for units.
							Can conformance be validated or ensured?
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="type" type="nx:primitiveType" default="NX_CHAR"/>
				<xs:attribute name="minOccurs" use="optional" default="0">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="maxOccurs" use="optional"  default="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="enumerationType">
		<xs:sequence>
			<xs:element name="item" type="nx:enumItemType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="enumItemType">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="value" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== Acidburn0zzz/definitions/base_classes/NXmoderator.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXmoderator" 
	type="group" extends="NXobject">
    <doc>This is the description for a general moderator</doc>
    <group type="NXgeometry">
        <doc>"Engineering" position of moderator</doc>
    </group>
    <field name="distance" type="NX_FLOAT">
        <doc>Effective distance as seen by measuring radiation</doc>
    </field>
    <field name="type">
        <enumeration>
            <item value="H20"/>
            <item value="D20"/>
            <item value="Liquid H2"/>
            <item value="Liquid CH4"/>
            <item value="Liquid D2"/>
            <item value="Solid D2"/>
            <item value="C"/>
            <item value="Solid CH4"/>
            <item value="Solid H2"/>
        </enumeration>
    </field>
    <field name="poison_depth" type="NX_FLOAT" units="NX_LENGTH"/>
    <field name="coupled" type="NX_BOOLEAN">
        <doc>whether the moderator is coupled</doc>
    </field>
    <field name="poison_material">
        <enumeration>
            <item value="Gd"/>
            <item value="Cd"/>
        </enumeration>
    </field>
    <field name="temperature" type="NX_FLOAT" units="NX_TEMPERATURE">
        <doc>average/nominal moderator temperature</doc>
    </field>
    <group type="NXlog" name="temperature_log">
        <doc>log file of moderator temperature</doc>
    </group>
    <group type="NXdata" name="pulse_shape">
        <doc>moderator pulse shape</doc>
    </group>
</definition>

=== Acidburn0zzz/definitions/applications/NXreftof.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date: 2009-05-13 16:24:58 +0200 (Wed, 13 May 2009) $
# $Author: Pete Jemian $
# $Revision: 350 $
# $HeadURL: https://svn.nexusformat.org/definitions/trunk/applications/NXmonopd.nxdl.xml $
# $Id: NXmonopd.nxdl.xml 350 2009-05-13 14:24:58Z Pete Jemian $
########### SVN repository information ###################
-->
<definition name="NXreftof" extends="NXobject" type="group"
    xmlns="http://definition.nexusformat.org/nxdl/3.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd ">
    <doc>This is an application definition for raw data from a TOF reflectometer. </doc>
    <group type="NXentry" name="entry">
      <field name="title" />
      <field name="start_time" type="NX_DATE_TIME" />
      <field name="end_time" type="NX_DATE_TIME" />
      <field name="definition">
        <doc>
          Official NeXus DTD or NXDL schema to which this file conforms
        </doc>
        <enumeration>
          <item value="NXreftof"></item>
        </enumeration>
      </field>
      <group type="NXinstrument" name="instrument">
        <field name="name" type="NX_CHAR"></field>
        <group type="NXdisk_chopper" name="chopper">
          <field name="distance" type="NX_FLOAT" units="NX_LENGTH">
            <doc>Distance between chopper and sample</doc>
          </field>
        </group>
        <group type="NXdetector">
          <field name="data" type="NX_INT">
            <dimensions size="3">
              <dim index="1" value="xsize" /><dim index="2" value="ysize" /><dim
                index="3" value="nTOF" />
            </dimensions>
          </field>
          <field name="time_of_flight" type="NX_FLOAT" units="NX_TIME_OF_FLIGHT">
            <doc>
              Array of time values for each bin in a time-of-flight measurement
            </doc>
            <dimensions size="1">
              <dim index="1" value="nTOF" /></dimensions>
          </field>
          <field name="distance" type="NX_FLOAT" units="NX_LENGTH"></field>
          <field name="polar_angle" type="NX_FLOAT" units="NX_ANGLE"></field>
          <field name="x_pixel_size" type="NX_FLOAT" units="NX_LENGTH">
          </field>
          <field name="y_pixel_size" type="NX_FLOAT" units="NX_LENGTH">
          </field>
         </group>
      </group>
      <group type="NXsample" name="sample">
        <field name="name">
          <doc>Descriptive name of sample</doc>
        </field>
        <field name="rotation_angle" type="NX_FLOAT" units="NX_ANGLE"></field>
      </group>
      <group type="NXmonitor">
        <field name="mode">
          <doc>
            Count to a preset value based on either clock time (timer)
            or received monitor counts (monitor).
          </doc>
          <enumeration>
            <item value="monitor" />
            <item value="timer" />
          </enumeration>
        </field>
        <field name="preset" type="NX_FLOAT" units="NX_ANY">
          <doc>preset value for time or monitor</doc>
        </field>
        <field name="integral" type="NX_INT">
          <doc>Total integral monitor counts</doc>
        </field>
        <field name="time_of_flight" type="NX_FLOAT" units="NX_TIME_OF_FLIGHT" axis="1">
          <doc>Time channels</doc>
        </field>
        <field name="data" type="NX_INT" signal="1">
          <doc>Monitor counts in each time channel</doc>
        </field>
      </group>
      <group type="NXdata" name="data">
          <field name="data" type="NX_INT">
            <doc>Link to /entry/instrument/detector/data</doc>
            <dimensions size="3">
              <dim index="1" value="xsize" />
              <dim index="2" value="ysize" />
              <dim index="3" value="nTOF" />
            </dimensions>
          </field>
        <field name="time_of_flight" type="NX_FLOAT" units="NX_TIME_OF_FLIGHT">
            <doc>Link to /entry/instrument/detector/time_binning</doc>
            <dimensions size="1">
              <dim index="1" value="nTOF" />
            </dimensions>
        </field>
      </group>
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXevent_data.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXevent_data" 
	type="group" extends="NXobject">
	<doc>Time-of-flight events</doc>
	<field name="time_of_flight" type="NX_INT" units="10^n second">
		<doc>
			A list of time of flight for each event as it comes in. 
			This list is for all pulses with information to attach 
			to a particular pulse located in events_per_pulse.
		</doc>
		<dimensions>i</dimensions>
	</field>
	<field name="pixel_number" type="NX_INT">
		<doc>
			There will be extra information in the NXdetector to convert 
			pixel_number to detector_number. This list is for all pulses with 
			information to attach to a particular pulse located in events_per_pulse.
		</doc>
		<dimensions>i</dimensions>
	</field>
	<field name="pulse_time" type="NX_INT" units="10^n second">
		<doc>
			The time that each pulse started with respect to the offset
		</doc>
		<dimensions>j</dimensions>
		<attribute name="offset" type="NX_CHAR">
			<doc>ISO8601</doc>
		</attribute>
	</field>
	<field name="events_per_pulse" type="NX_INT">
		<doc>
			This connects the index "i" to the index "j". 
			The jth element is the number of events in "i" 
			that occurred during the jth pulse.
		</doc>
		<dimensions>j</dimensions>
	</field>
	<field name="pulse_height" type="NX_FLOAT" units="">
		<doc>
			If voltages from the ends of the detector are read out this 
			is where they go. This list is for all events with information 
			to attach to a particular pulse height. The information to 
			attach to a particular pulse is located in events_per_pulse.
		</doc>
		<dimensions>i,k?</dimensions>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXmonochromator.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXmonochromator" 
	type="group" extends="NXobject">
    <doc>This is a base class for everything which selects a wavelength or energy, be it a
    monochromator crystal, a velocity selector, a undulator or whatever
    
    expected units
    wavelength: angstrom
    energy:     eV
    </doc>
    <field name="wavelength" type="NX_FLOAT" units="NX_WAVELENGTH">
        <doc>wavelength selected</doc>
        <dimensions>[]</dimensions>
    </field> 
    <field name="wavelength_error" type="NX_FLOAT" units="NX_WAVELENGTH">
        <doc>wavelength standard deviation</doc>
        <dimensions>[]</dimensions>
    </field> 
    <field name="energy" type="NX_FLOAT" units="NX_ENERGY">
        <doc>energy selected</doc>
        <dimensions>[]</dimensions>
    </field> 
    <field name="energy_error" type="NX_FLOAT" units="NX_ENERGY">
        <doc>energy standard deviation</doc>
        <dimensions>[]</dimensions>
    </field> 
    <group type="NXdata" name="distribution"/> 
</definition>

=== Acidburn0zzz/definitions/base_classes/NXcollimator.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/schema/3.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/schema/3.1 ../nxdl.xsd"
    name="NXcollimator" 
    type="group" extends="../nxdl">

    <doc>Template of a beamline collimator.</doc>
    <group type="NXgeometry">
        <doc>position, shape and size</doc>
    </group>
    <field name="type">
        <enumeration>
            <item value="Soller"/>
            <item value="radial"/>
            <item value="oscillating"/>
            <item value="honeycomb"></item>
        </enumeration>
    </field>
    <field name="soller_angle" type="NX_FLOAT" units="NX_TIME">
        <doc>Angular divergence of Soller collimator</doc>
    </field>
    <field name="divergence_x" type="NX_FLOAT">
        <doc>divergence of collimator in local x direction</doc>
    </field>
    <field name="divergence_y" type="NX_FLOAT">
        <doc>divergence of collimator in local y direction</doc>
    </field>
    <field name="frequency" type="NX_FLOAT">
        <doc>Frequency of oscillating collimator</doc>
    </field>
    <group type="NXlog" name="frequency_log">
        <doc>Log of frequency</doc>
    </group>
    <field name="blade_thickness" type="NX_FLOAT">
    </field>
    <field name="blade_spacing" type="NX_FLOAT">
    </field>
    <field name="absorbing_material">
    </field>
    <field name="transmitting_material">
    </field>
</definition>

=== Acidburn0zzz/definitions/applications/NXtomophase.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date: 2009-05-13 16:24:58 +0200 (Wed, 13 May 2009) $
# $Author: Pete Jemian $
# $Revision: 350 $
# $HeadURL: https://svn.nexusformat.org/definitions/trunk/applications/NXmonopd.nxdl.xml $
# $Id: NXmonopd.nxdl.xml 350 2009-05-13 14:24:58Z Pete Jemian $
########### SVN repository information ###################
-->
<definition name="NXtomophase" extends="NXobject" type="group"
    xmlns="http://definition.nexusformat.org/nxdl/3.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd ">
    <doc>This is the application definition for x-ray or neutron tomography raw data with phase contrast variation at each point. In tomography first 
          some dark field images are measured, some bright field images and, of course the sample. In order 
          to properly sort the order of the images taken, a sequence number is stored with each image.</doc>
    <group type="NXentry" name="entry">
      <field name="title" />
      <field name="start_time" type="NX_DATE_TIME" />
      <field name="end_time" type="NX_DATE_TIME" />
      <field name="definition">
        <doc>
          Official NeXus DTD or NXDL schema to which this file conforms
        </doc>
        <enumeration>
          <item value="NXtomo"></item>
        </enumeration>
      </field>
      <group type="NXinstrument" name="instrument">
        <group type="NXsource">
          <field name="type" />
          <field name="name" />
          <field name="probe">
            <enumeration>
              <item value="neutron" />
              <item value="x-ray" />
              <item value="electron" />
            </enumeration>
          </field>
        </group>
        <group type="NXdetector" name="bright_field">
          <field name="data" type="NX_INT">
            <dimensions size="3">
              <dim index="1" value="nBrightFrames" /><dim index="2"
                value="xsize" /><dim index="3" value="ysize" />
            </dimensions>
          </field>
          <field name="sequence_number">
            <dimensions size="1">
              <dim index="1" value="nBrightFrames" />
            </dimensions></field>
        </group>
        <group type="NXdetector" name="dark_field">
          <field name="data" type="NX_INT">
            <dimensions size="3">
              <dim index="1" value="nDarkFrames" /><dim index="2"
                value="xsize" /><dim index="3" value="ysize" />
            </dimensions>
          </field>
          <field name="sequence_number">
            <dimensions size="1">
              <dim index="1" value="nDarkFrames" />
            </dimensions></field>
        </group>
        <group type="NXdetector" name="sample">
          <field name="data" type="NX_INT">
            <dimensions size="4">
              <dim index="1" value="nSampleFrames" /><dim index="2"
                value="nPhase" /><dim index="3" value="xsize" /><dim
                index="4" value="ysize" />
            </dimensions>
          </field>
          <field name="sequence_number">
            <dimensions size="2">
              <dim index="1" value="nSampleFrames" /><dim index="2"
                value="nPhase" />
            </dimensions></field>
          <field name="x_pixel_size" type="NX_FLOAT" units="NX_LENGTH"></field>
          <field name="y_pixel_size" type="NX_FLOAT" units="NX_LENGTH"></field>
          <field name="distance" type="NX_FLOAT" units="NX_LENGTH">
            <doc>Distance between detector and sample</doc></field>
        </group>
      </group>
      <group type="NXsample" name="sample">
        <field name="name">
          <doc>Descriptive name of sample</doc>
        </field>
        <field name="rotation_angle" type="NX_FLOAT" units="NX_ANGLE">
          <dimensions size="1">
            <dim index="1" value="nSampleFrames" /></dimensions></field>
      </group>
      <group type="NXmonitor" name="control">
        <field name="integral" type="NX_FLOAT" units="NX_ANY">
          <doc>Total integral monitor counts for each measured frame. This is in order to correct for fluctuations in the beam between frames</doc>
          <dimensions size="1">
            <dim index="1" value="nDarkFrames + nBrightFrames + nSampleFrame" /></dimensions>
        </field>
      </group>
      <group type="NXdata" name="data">
          <field name="data" type="NX_INT">
            <doc>Link to /entry/instrument/sample/data</doc>
            <dimensions size="4">
              <dim index="1" value="nSampleFrames" /><dim index="2"
                value="nPhase" /><dim index="3" value="xsize" /><dim
                index="4" value="ysize" />
            </dimensions>
          </field>
        <field name="rotation_angle" type="NX_FLOAT" units="NX_ANGLE">
          <doc>Link to /entry/sample/rotation_angle</doc>
          <dimensions size="1">
            <dim index="1" value="nSampleFrames" /></dimensions></field>
        </group>
    </group>
</definition>
