=== Acidburn0zzz/definitions/nxdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $LastChangedDate$
# $LastChangedBy$
# $LastChangedRevision$
# $HeadURL$
########### SVN repository information ###################
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://definition.nexusformat.org/nxdl/3.1"
	xmlns:nx="http://definition.nexusformat.org/nxdl/3.1" 
	version="$Id$"
	elementFormDefault="qualified">

	<xs:annotation>
		<xs:documentation>
			# NeXus - Neutron and X-ray Common Data Format
			# 
			# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
			# 
			# This library is free software; you can redistribute it and/or
			# modify it under the terms of the GNU Lesser General Public
			# License as published by the Free Software Foundation; either
			# version 2 of the License, or (at your option) any later version.
			#
			# This library is distributed in the hope that it will be useful,
			# but WITHOUT ANY WARRANTY; without even the implied warranty of
			# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
			# Lesser General Public License for more details.
			#
			# You should have received a copy of the GNU Lesser General Public
			# License along with this library; if not, write to the Free Software
			# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
			#
			# For further information, see http://www.nexusformat.org
		</xs:documentation>
	</xs:annotation>
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	
	<xs:include schemaLocation="nxdlTypes.xsd">
		<xs:annotation>
			<xs:documentation>
				Definitions of the basic data types and unit types 
				allowed in NXDL instance files.
			</xs:documentation>
		</xs:annotation>
	</xs:include>
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	
	<!-- define the document root element -->
	<xs:element name="definition" type="nx:definitionType" />
	
	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="definitionType">
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded" />
		<xs:attribute name="name" use="required" />
		<xs:attribute name="type" use="required" type="nx:definitionTypeAttr" />
		<xs:attribute name="extends" use="required" />
		<xs:attribute name="svnid" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="attributeType">
		<xs:annotation>
			<xs:documentation>
				A new element may expect or require some attributes.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" />
			<xs:element name="enumeration" type="nx:enumerationType"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>The field can have an enumeration of values</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" />
		<xs:attribute name="type" type="nx:primitiveType" default="NX_CHAR"/>
	</xs:complexType>

	<xs:simpleType name="definitionTypeAttr">
		<xs:restriction base="xs:string">
			<xs:enumeration value="group" />
			<xs:enumeration value="definition" />
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="groupGroup">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="attribute" type="nx:attributeType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="group" type="nx:groupType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="field" type="nx:fieldType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="basicComponent">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" use="required" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:simpleType name="docType">
		<xs:annotation>
			<xs:documentation>
				This is the basic definition of a new type.
				Components must derive from an existing type 
				and optionally provide documentation.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="groupType">
		<xs:annotation>
			<xs:documentation>
				A group element will be used to refer to an existing NX object or locally-defined component.
			</xs:documentation>
		</xs:annotation>
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="NX.+"></xs:pattern>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="minOccurs" use="optional" default="0" type="xs:nonNegativeInteger"/>
		<xs:attribute name="maxOccurs" use="optional"  default="unbounded"/>
		<xs:attribute name="name" use="optional" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="dimsType">
		<!--
			Here is a model:
			<field name="data">
			    <dimensions size="3"/>
			    ...
			</field><field name="time-of-flight">
				<dimensions size="1">
					<dim index="1" ref="data" refindex="3" incr="1"/>
				</dimensions>
				...
			</field>
			
			In old terms this would make data[i,j,k] and time-of-flight[k+1]. 
			We need to get to the stage where people
			don't need to read a manual to understand an existing NXDL.
		-->
		<xs:annotation>
			<xs:documentation>dimensions of a data element in a NeXus file</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="dim" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:attribute name="index" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Number indicating which subscript is being referenced, 
								ranging from 1 up to RANK (rank of the data structure).  For example, 
								given an array A[i,j,k], index="1" would refer to the "i" subscript.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="ref" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Name of the data structure being referenced indirectly.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="refindex" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>Index within the data structure being referenced indirectly.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="incr" type="nx:NX_CHAR">
						<xs:annotation>
							<xs:documentation>What is this?</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="size" type="nx:NX_CHAR">
			<xs:annotation>
				<xs:documentation>Rank (number of dimensions) of the data structure.  
					For example: a[5] has size="1" while b[8,5,6,4] has size="4".  
					See http://en.wikipedia.org/wiki/Rank_(computer_programming) 
					for more details.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:annotation>
				<xs:documentation>A field element will be used to declare a new element in the component being defined.</xs:documentation>
			</xs:annotation>
			<xs:extension base="nx:basicComponent">
				<xs:sequence>
					<xs:element name="dimensions" type="nx:dimsType"
						minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>dimensions of a data element in a NeXus file</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="attribute" type="nx:attributeType"
						minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>attributes of field</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="enumeration" type="nx:enumerationType"
						minOccurs="0">
						<xs:annotation>
							<xs:documentation>The field can have an enumeration of values</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="units" type="nx:anyUnitsAttr">
					<xs:annotation>
						<xs:documentation>
							String describing the engineering units.
							The string should be appropriate for the value
							and should conform to the NeXus rules for units.
							Can conformance be validated or ensured?
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="type" type="nx:primitiveType" default="NX_CHAR"/>
				<xs:attribute name="minOccurs" use="optional" default="0">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="maxOccurs" use="optional"  default="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="enumerationType">
		<xs:sequence>
			<xs:element name="item" type="nx:enumItemType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="enumItemType">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="value" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== Acidburn0zzz/definitions/base_classes/NXsource.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/schema/3.1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://definition.nexusformat.org/schema/3.1 ../nxdl.xsd"
    name="NXsource" 
	type="group" extends="NXobject">
	<doc>Template of the neutron or x-ray source, insertion devices and/or moderators.</doc>
	<field name="distance" type="NX_FLOAT" units="NX_LENGTH">
		<doc>
			Effective distance from sample
			Distance as seen by radiation from sample. This number should be negative 
			to signify that it is upstream of the sample.
		</doc>
	</field>
	<field name="name">
		<doc>
			Name of source
		</doc>
	</field>
	<field name="type">
		<doc>type of radiation source</doc>
		<enumeration>
			<item value="Spallation Neutron Source" />
			<item value="Pulsed Reactor Neutron Source" />
			<item value="Reactor Neutron Source" />
			<item value="Synchrotron X-ray Source" />
			<item value="Pulsed Muon Source" />
			<item value="Rotating Anode X-ray" />
			<item value="Fixed Tube X-ray" />
		</enumeration>
	</field>
	<field name="probe">
		<doc>type of radiation probe</doc>
		<enumeration>
			<item value="neutron" />
			<item value="x-ray" />
			<item value="muon" />
			<item value="electron" />
		</enumeration>
	</field>
	<field name="power" type="NX_FLOAT" units="NX_POWER">
		<doc>Source power</doc>
	</field>
	<field name="current" type="NX_FLOAT" units="NX_CURRENT">
		<doc>Accelerator current</doc>
	</field>
	<field name="voltage" type="NX_FLOAT" units="NX_VOLTAGE">
		<doc>Accelerator voltage</doc>
	</field>
	<field name="frequency" type="NX_FLOAT" units="NX_FREQUENCY">
		<doc>Frequency of pulsed source</doc>
	</field>
	<field name="period" type="NX_FLOAT" units="NX_PERIOD">
		<doc>Period of pulsed source</doc>
	</field>
	<field name="target_material">
		<doc>Pulsed source target material</doc>
		<enumeration>
			<item value="Ta" />
			<item value="W" />
			<item value="depleted_U" />
			<item value="enriched_U" />
			<item value="Hg" />
			<item value="Pb" />
			<item value="C" />
		</enumeration>
	</field>
	<field name="notes">
		<doc>
			any source/facility related messages/events that 
			occurred during the experiment
		</doc>
	</field>
	<field name="pulse_width" type="NX_FLOAT" units="NX_TIME">
		<doc>width of source pulse</doc>
	</field>
	<group name="pulse_shape" type="NXdata">
		<doc>source pulse shape</doc>
	</group>
	<field name="mode">
		<doc>source operating mode</doc>
		<enumeration>
			<item value="Single Bunch" />
			<item value="Multi Bunch" />
		</enumeration>
	</field>
	<field name="top_up" type="NX_BOOLEAN">
		<doc>Is the synchrotron operating in top_up mode?</doc>
	</field>
	<group name="geometry" type="NXgeometry">
		<doc>"Engineering" location of source</doc>
	</group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXfilter.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008-2010 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/nxdl/3.1" category="base"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
	name="NXfilter" 
	version="1.0"
    svnid="$Id$"
	type="group" extends="NXobject">
	<doc>Template for specifying the state of band pass filters</doc>
	<group type="NXgeometry">
		<doc>Geometry of the filter</doc>
	</group>
	<field name="description">
		<doc>Composition of the filter. Choose only one from the enumerated list and spell exactly.
		Contact the NIAC if you wish to add to the list.</doc>
		<!-- TODO relax from an enumeration to a string and handle a wider variety of materials
			TODO move the enumeration strings to the documentation note
			TODO also need to add these as fields
				thickness
				density
				chemical formula (this could be the relax version of the description field)
		-->
		<enumeration>
			<item value="Beryllium" />
			<item value="Pyrolytic Graphite" />
			<item value="Graphite" />
			<item value="Sapphire" />
			<item value="Silicon" />
			<item value="Supermirror" />
		</enumeration>
	</field>
	<field name="status">
		<doc>position with respect to in or out of the beam (choice of only "in" or "out")</doc>
		<enumeration>
			<item value="in"><doc>in the beam</doc></item>
			<item value="out"><doc>out of the beam</doc></item>
		</enumeration>
	</field>
	<group name="transmission" type="NXdata">
		<doc>Wavelength transmission profile of filter</doc>
	</group>
	<field name="temperature" type="NX_FLOAT" units="NX_TEMPERATURE">
		<doc>average/nominal filter temperature</doc>
	</field>
	<group name="temperature_log" type="NXlog">
		<doc>Linked temperature_log for the filter</doc>
	</group>
	<group name="sensor_type" type="NXsensor">
		<doc>Sensor(s)used to monitor the filter temperature</doc>
	</group>
	<field name="unit_cell_a" type="NX_FLOAT" units="NX_LENGTH">
		<doc>Unit cell lattice parameter: length of side a</doc>
	</field>
	<field name="unit_cell_b" type="NX_FLOAT" units="NX_LENGTH">
		<doc>Unit cell lattice parameter: length of side b</doc>
	</field>
	<field name="unit_cell_c" type="NX_FLOAT" units="NX_LENGTH">
		<doc>Unit cell lattice parameter: length of side c</doc>
	</field>
	<field name="unit_cell_alpha" type="NX_FLOAT" units="NX_ANGLE">
		<doc>Unit cell lattice parameter: angle alpha</doc>
	</field>
	<field name="unit_cell_beta" type="NX_FLOAT" units="NX_ANGLE">
		<doc>Unit cell lattice parameter: angle beta</doc>
	</field>
	<field name="unit_cell_gamma" type="NX_FLOAT" units="NX_ANGLE">
		<doc>Unit cell lattice parameter: angle gamma</doc>
	</field>
	<field name="unit_cell_volume" type="NX_FLOAT" units="NX_VOLUME">
		<doc>Unit cell</doc>
		<dimensions rank="1"><dim index="1" value="n_comp"/></dimensions>
	</field>
	<field name="orientation_matrix" type="NX_FLOAT">
		<doc>Orientation matrix of single crystal filter</doc>
		<dimensions rank="3"><!--n_comp,3,3-->
			<dim index="1" value="n_comp"/>
			<dim index="2" value="3"/>
			<dim index="3" value="3"/>
		</dimensions>
	</field>
	<field name="m_value" type="NX_FLOAT" units="NX_DIMENSIONLESS">
		<doc>m value of supermirror filter</doc>
	</field>
	<field name="substrate_material">
		<doc>substrate material of supermirror filter</doc>
	</field>
	<field name="substrate_thickness" type="NX_FLOAT" units="NX_LENGTH">
		<doc>substrate thickness of supermirror filter</doc>
	</field>
	<field name="coating_material">
		<doc>coating material of supermirror filter</doc>
	</field>
	<field name="substrate_roughness" type="NX_FLOAT" units="NX_LENGTH">
		<doc>substrate roughness (RMS) of supermirror filter</doc>
	</field>
	<field name="coating_roughness" type="NX_FLOAT" units="NX_LENGTH">
		<doc>coating roughness (RMS) of supermirror filter</doc>
		<dimensions rank="1"><dim incr="1" value="nsurf"/></dimensions>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXbeam_stop.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXbeam_stop"
    type="group" extends="NXobject">
    <doc>A class for a beamstop. Beamstops and their positions are important for SANS
    and SAXS experiments.</doc>
    <group type="NXgeometry">
        <doc>engineering shape, orientation and position of the beam stop.</doc>
    </group>
    <field name="description" type="NX_CHAR">
        <doc>description of beamstop</doc>
        <enumeration>
            <item value="circular"/>
            <item value="rectangular"/>
        </enumeration>
        </field>
    <field name="size" type="NX_FLOAT" units="cm">
        <doc>size of beamstop</doc>
    </field>
    <field name="x" type="NX_FLOAT" units="cm">
        <doc>x position of the beamstop in relation to the detector</doc>
    </field>
    <field name="y" type="NX_FLOAT" units="cm">
        <doc>y position of the beamstop in relation to the detector</doc>
    </field>
    <field name="distance_to_detector" type="NX_FLOAT" units="cm">
        <doc>distance of the beamstop to the detector</doc>
    </field>
    <field name="status" type="NX_CHAR">
        <enumeration>
            <item value="in"/>
            <item value="out"/>
        </enumeration>
    </field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXguide.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXguide" 
	type="group" extends="NXobject">
    <doc>Template of NXguide</doc>
    <group type="NXgeometry"/>
    <field name="description" type="NX_CHAR"/>
    <field name="incident_angle" type="NX_FLOAT"/>
    <group type="NXdata" name="reflectivity">
        <doc>Reflectivity as function of wavelength [nsurf,i]</doc>
    </group>
    <field name="bend_angle_x" type="NX_FLOAT"/>
    <field name="bend_angle_y" type="NX_FLOAT"/>
    <field name="interior_atmosphere" type="NX_CHAR">
        <enumeration>
            <item value="vacuum"/>
            <item value="helium"/>
            <item value="argon"/>
        </enumeration>
    </field>
    <field name="external_material" type="NX_CHAR">
        <doc>external material outside substrate</doc>
    </field>
    <field name="m_value" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="substrate_material" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="substrate_thickness" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="coating_material" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="substrate_roughness" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="coating_roughness" type="NX_FLOAT">
        <dimensions>nsurf</dimensions>
    </field>
    <field name="number_sections" type="NX_INT">
        <doc>number of substrate sections</doc>
    </field>
</definition>

=== Acidburn0zzz/definitions/applications/NXmonopd.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date: 2009-01-16 20:21:39 +0100 (Fri, 16 Jan 2009) $
# $Author: Mark Koennecke $
# $Revision: 261 $
# $HeadURL: https://svn.nexusformat.org/definitions/trunk/applications/NXmonopd.xml $
# $Id: $
########### SVN repository information ###################
-->
<nx:definition extends="" name="" type="group" xmlns:nx="http://definition.nexusformat.org/schema/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://definition.nexusformat.org/schema/3.1 ../nxdl.xsd ">
	<nx:group type="NXentry">
		<nx:field name="title" type="NX_CHAR"></nx:field>
		<nx:field name="start_time" type="NX_DATE_TIME"></nx:field>
		<nx:field name="end_time" type="NX_DATE_TIME"></nx:field>
		<nx:group type="NXinstrument">
			<nx:group type="NXsource">
				<nx:field name="type" type="NX_CHAR"></nx:field>
				<nx:field name="name" type="NX_CHAR"></nx:field>
				<nx:field name="probe" type="NX_CHAR">
					<nx:enumeration>
						<nx:item value="neutron"></nx:item>
						<nx:item value="x-ray"></nx:item>
						<nx:item value="electron"></nx:item>
					</nx:enumeration></nx:field></nx:group>
			<nx:group type="NXcrystal">
    <nx:field name="wavelength" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Optimum diffracted wavelength</doc>
        <dimensions>i</dimensions>
    </nx:field>

                        </nx:group>
			<nx:group type="NXdetector">
				<nx:field name="polar_angle" type="NX_FLOAT">
					<nx:dimensions>number of detectors</nx:dimensions></nx:field>
				<nx:field name="data" type="NX_INT32">
					<nx:dimensions>number of detectors</nx:dimensions></nx:field>
				<nx:field name="efficiency" type="NX_FLOAT">
					<nx:doc>efficiency of each detecor</nx:doc><nx:dimensions>number of detectors</nx:dimensions></nx:field>
				</nx:group></nx:group></nx:group>
	<nx:group type="NXsample">
	<nx:field name="name">
		<doc>Descriptive name of sample</doc>
	</nx:field>
	<nx:field name="rotation_angle" type="NX_FLOAT" units="NX_ANGLE">
		<doc>
			Optional rotation angle for the case when the powder diagram has 
			been obtained through an omega-2theta scan like from a traditional 
			single detector powder diffractometer
		</doc>
	</nx:field>
        </nx:group>
	<nx:group type="NXmonitor">
    <nx:field name="mode">
        <enumeration>
            <item value="monitor"/>
            <item value="timer"/>
        </enumeration>
    </nx:field>
    <nx:field name="preset" type="NX_FLOAT">
        <doc>preset value for time or monitor</doc>
    </nx:field>
    <nx:field name="integral" type="NX_FLOAT" units="NX_ANY">
        <doc>Total integral monitor counts</doc>
    </nx:field>
        </nx:group>
	<nx:group type=" NXdata">
				<nx:field name="polar_angle" type="NX_FLOAT">
					<nx:doc>Link to polar angle in /NXentry/NXinstrument/NXdetector</nx:doc>
					<nx:dimensions>number of detectors or data points</nx:dimensions></nx:field>
				<nx:field name="data" type="NX_INT">
					<nx:doc>Link to data in /NXentry/NXinstrument/NXdetector</nx:doc>
					<nx:dimensions>number of detectors or data points</nx:dimensions></nx:field>
</nx:group>
</nx:definition>
