=== Acidburn0zzz/definitions/base_classes/nxdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsd-documentation.xsl" ?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.nexusformat.org"
	xmlns:nx="http://www.nexusformat.org"
	elementFormDefault="qualified">
	
	<!-- define the document root element -->
	<xs:element name="definition" type="nx:definitionType" />

	<xs:complexType name="definitionType">
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded" />
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type" use="required" type="nx:definitionTypeAttr"/>
		<xs:attribute name="extends" use="required"/>
	</xs:complexType>

	<xs:simpleType name="definitionTypeAttr">
		<xs:restriction base="xs:string">
			<xs:enumeration value="group"/>
			<xs:enumeration value="definition"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="groupGroup">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="group" type="nx:groupType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field" type="nx:fieldType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="basicComponent">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="type" use="required" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:simpleType name="docType">
		<xs:annotation>
			<xs:documentation>
				This is the basic definition of a new type.
				Components must derive from an existing type 
				and optionally provide documentation.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:complexType name="groupType">
		<xs:annotation>
			<xs:documentation>
				A group element will be used to refer to an existing NX object or locally-defined component.
			</xs:documentation>
		</xs:annotation>
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" use="required"></xs:attribute>
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:annotation>
				<xs:documentation>
					A field element will be used to declare a new element in the component being defined.
    	       	</xs:documentation>
			</xs:annotation>
			<xs:extension base="nx:basicComponent">
				<xs:sequence>
					<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>
								A new element may expect or require some attributes.
    	    			   	</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="name" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== Acidburn0zzz/definitions/base_classes/NXgeometry.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXgeometry" 
	type="group" extends="NXobject">
    <doc>This is the description for a general position of a component. Note that every instance of
        an NXgeometry should be named "geometry" so that it can be linked to (linked items must
        share the same name in HDF)</doc>
    <group type="NXshape">
        <doc>shape/size information of component</doc>
    </group>
    <group type="NXtranslation">
        <doc>translation of component</doc>
    </group>
    <group type="NXorientation">
        <doc>orientation of component</doc>
    </group>
    <field name="description">
        <doc>Optional description/label. Probably only present if we are an additional reference
            point for components rather than the location of a real component</doc>
    </field>
    <field name="component_index" type="NX_INT">
        <doc>Position of the component along the beam path. The sample is at 0, components upstream
            have negative component_index, components downstream have positive
        component_index.</doc>
    </field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXentry.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXentry" 
	type="group" extends="NXobject">
	<doc>
		Template of the top-level NeXus group which contains all the data and associated information that comprise a single measurement. It is mandatory that there is at least one group of this type in the NeXus file.
	</doc>
	<field name="title" type="NX_CHAR"><doc>Extended title for entry</doc></field>
	<field name="experiment_identifier" type="NX_CHAR" dims="[]"><doc>Unique identifier for the experiment, defined by the facility, possibly linked to the proposals</doc></field>
	<field name="experiment_description" type="NX_CHAR"><doc>Brief summary of the experiment, including key objectives.</doc></field>
	<group type="NXnote"  name="experiment_documentation"><doc>Description of the full experiment (document in pdf, latex, â€¦)</doc></group>
	<field name="collection_identifier" type="NX_CHAR"><doc>User or Data Acquisition defined group of NeXus files or NXentry</doc></field>
	<field name="collection_description" type="NX_CHAR"><doc>Brief summary of the collection, including grouping criteria.</doc></field>
	<field name="entry_identifier" type="NX_CHAR"><doc>unique identifier for the measurement, defined by the facility.</doc></field>
	<field name="definition" type="NX_CHAR">
		<doc>Name of entry DTD</doc>
		<attribute name="version" type="NX_CHAR"><doc>DTD version number</doc></attribute>
		<attribute name="URL" type="NX_CHAR"><doc>URL of DTD file</doc></attribute>
	</field>
	<field name="definition_local" type="NX_CHAR">
		<doc>Name of entry DTD</doc>
		<attribute name="version" type="NX_CHAR"><doc>DTD version number</doc></attribute>
		<attribute name="URL" type="NX_CHAR"><doc>URL of DTD file</doc></attribute>
	</field>
	<field name="start_time" type="ISO8601"><doc>Starting time of measurement</doc></field>
	<field name="end_time" type="ISO8601"><doc>Ending time of measurement</doc></field>
	<field name="duration" type="NX_INT" units="seconds"><doc>Duration of measurement</doc></field>
	<field name="collection_time" type="NX_FLOAT" units="seconds">
		<doc>
			Time transpired actually collecting data i.e. taking out time when collection was suspended due to e.g. temperature out of range
		</doc>
	</field>
	<field name="run_cycle" type="NX_CHAR" dims="[]" />
	<field name="program_name" type="NX_CHAR">
		<doc>Name of program used to generate this file</doc>
		<attribute name="version" type="NX_CHAR"><doc>{Program version number</doc></attribute>
		<attribute name="configuration" type="NX_CHAR"><doc>{configuration of the program</doc></attribute>
	</field>
	<field name="revision" type="NX_CHAR">
		<doc>Revision id of the file due to re-calibration, reprocessing, new analysis, new instrument definition format, ...</doc>
		<attribute name="comment" type="NX_CHAR" />
	</field>
	<field name="notes" type="NX_CHAR"><doc>Notes describing entry</doc></field>
	<group name="thumbnail" type="NXnote">
		<doc>
			A small image that is representative of the entry.
			An example of this is a 640x480 jpeg image automatically produced by a low resolution plot of the NXdata.
		</doc>
		<attribute name="mime_type" type="NX_CHAR">
			<enumeration>
				<item value="image/*" />
			</enumeration>
		</attribute>
	</group>
	<group type="NXcharacterization" />
	<group type="NXuser" />
	<group type="NXsample" />
	<group type="NXinstrument" />
	<group type="NXmonitor" />
	<group type="NXdata" />
	<group type="NXprocess" />
</definition>

=== Acidburn0zzz/definitions/base_classes/NXaperture.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXaperture" type="group" extends="NXobject">
    <doc>Template of a beamline aperture.</doc>
    <group type="NXgeometry">
        <doc>location and shape of aperture</doc>
    </group>
    <field name="material" type="NX_CHAR">
        <doc>Absorbing material of the aperture</doc>
    </field>
    <field name="description" type="NX_CHAR">
        <doc>Description of aperture</doc>
    </field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXvelocity_selector.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXvelocity_selector" 
	type="group" extends="NXobject">
	<doc>This is the description for a (typically neutron) velocity selector</doc>
	<field name="type">
		<doc>velocity selector type</doc>
	</field>
	<field name="rotation_speed" type="NX_FLOAT" units="NX_FREQUENCY">
		<doc>velocity selector rotation speed</doc>
	</field>
	<field name="radius" type="NX_FLOAT" units="NX_LENGTH">
		<doc>radius at beam centre</doc>
	</field>
	<field name="spwidth" type="NX_FLOAT" units="NX_LENGTH">
		<doc>spoke width at beam centre</doc>
	</field>
	<field name="length" type="NX_FLOAT" units="NX_LENGTH">
		<doc>rotor length</doc>
	</field>
	<field name="num" type="NX_INT">
		<doc>number of spokes/lamella</doc>
	</field>
	<field name="twist" type="NX_FLOAT" units="NX_ANGLE">
		<doc>twist angle along axis</doc>
	</field>
	<field name="table" type="NX_FLOAT" units="NX_ANGLE">
		<doc>offset vertical angle</doc>
	</field>
	<field name="height" type="NX_FLOAT" units="NX_LENGTH">
		<doc>input beam height</doc>
	</field>
	<field name="width" type="NX_FLOAT" units="NX_LENGTH">
		<doc>input beam width</doc>
	</field>
	<field name="wavelength" type="NX_FLOAT" units="NX_WAVELENGTH">
		<doc>wavelength</doc>
	</field>
	<field name="wavelength_spread" type="NX_FLOAT">
		<doc>deviation FWHM /Wavelength</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/contributed_definitions/NXtechnical_data.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NXtechnical_data: candidate NeXus base class definition

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/nxdl/3.1" category="contributed"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
    name="NXtechnical_data" version="1.0"
    svnid="$Id$" type="group"
    extends="NXobject">

    <doc>(definition implied by usage) Some measure of metadata not already considered by the other
        base classes. This class appears in the example data files provided from Soleil. This class
        should be considered as a base class (and relocated there, once approved by the NIAC). This
        class is used by Soleil as a child of (at least) these classes: NXsai_controller,
        NXdetector, NXsource </doc>

    <field name="data" type="NX_NUMBER" units="NX_ANY">
        <doc>The value(s) of this class. Examples from Soleil show this used as float (64-bit or
            32-bit), integer, or unsigned 8-bit char</doc>
        <attribute name="units">
            <doc>Engineering units</doc>
        </attribute>
        <attribute name="timestamp" type="NX_DATE_TIME">
            <doc>date and time when this value was obtained.</doc>
        </attribute>
        <attribute name="description">
            <doc>something useful about this data field</doc>
        </attribute>
    </field>

    <field name="description">
        <doc>{documentation for this instance of NXtechnical_data}</doc>
        <attribute name="description">
            <doc>something useful about this decription field</doc>
        </attribute>
    </field>

</definition>

=== Acidburn0zzz/definitions/base_classes/NXbeam.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXbeam"
    type="group" extends="NXobject">
    <doc>Template of the state of the neutron or X-ray beam at any location. It will be referenced
        by beamline component groups within the NXinstrument group or by the NXsample group. Note
        that variables such as the incident energy could be scalar values or arrays. This group is
        especially valuable in storing the results of instrument simulations in which it is useful
        to specify the beam profile, time distribution etc. at each beamline component. Otherwise,
        its most likely use is in the NXsample group in which it defines the results of the neutron
        scattering by the sample, e.g., energy transfer, polarizations. </doc>
    <field name="distance" type="NX_FLOAT" units="m">
        <doc>Distance from sample</doc>
    </field>
    <field name="incident_energy" type="NX_FLOAT" dims="[:]" units="meV">
        <doc>Energy on entering beamline component</doc>
    </field>
    <field name="final_energy" type="NX_FLOAT" dims="[:]" units="meV">
        <doc>Energy on leaving beamline component</doc>
    </field>
    <field name="energy_transfer" type="NX_FLOAT" dims="[:]" units="meV">
        <doc>Energy change caused by beamline component</doc>
    </field>
    <field name="incident_wavelength" type="NX_FLOAT" dims="[:]" units="Angstroms">
        <doc>Wavelength on entering beamline component</doc>
    </field>
    <field name="incident_wavelength_spread" type="NX_FLOAT" dims="[:]" units="Angstroms">
        <doc>Wavelength spread FWHM on entering component</doc>
    </field>
    <field name="incident_beam_divergence" type="NX_FLOAT" dims="[2,:]" units="degree">
        <doc>Divergence of beam entering this component</doc>
    </field>
    <field name="final_wavelength" type="NX_FLOAT" dims="[:]">
        <doc>Wavelength on leaving beamline component</doc>
    </field>
    <field name="incident_polarization" type="NX_FLOAT" dims="[3,:]">
        <doc>Polarization vector on entering beamline component</doc>
    </field>
    <field name="final_polarization" type="NX_FLOAT" dims="[3,:]">
        <doc>Polarization vector on leaving beamline component</doc>
    </field>
    <field name="final_wavelength_spread" type="NX_FLOAT" dims="[:]" units="Angstroms">
        <doc>Wavelength spread FWHM of beam leaving this component</doc>
    </field>
    <field name="final_beam_divergence" type="NX_FLOAT" dims="[2,:]" units="degrees">
        <doc>Divergence FWHM of beam leaving this component</doc>
    </field>
    <field name="flux" type="NX_FLOAT" dims="[i]" units="s-1cm-2">
        <doc>flux incident on beam plane area</doc>
    </field>
    <group type="NXdata">
        <doc>Distribution of beam with respect to relevant variable e.g. wavelength. This is mainly
            useful for simulations which need to store plottable information at each beamline
            component.</doc>
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXdata.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXdata" 
	type="group" extends="NXobject">
	<doc>
		Template of plottable data and their dimension scales. It is mandatory 
		that there is at least one group of this type in each NXentry group.  
		Note that "variable" and "data" can be defined with different names.  
		The "signal" and "axes" attribute of the "data" item define which items 
		are plottable data and which are dimension scales.
	</doc>
	<field name="variable" type="NX_FLOAT[:]|NX_INT[:]">
		<!-- 
			long_name="{Axis label}" distribution="0|1" 
			first_good="{Index of first good value}" 
			last_good="{Index of last good value}"
		 -->
	 	<doc>Dimension scale defining an axis of the data</doc>
	</field>
	<field name="variable_errors" type="NX_FLOAT[:]|NX_INT[:]">
		<doc>Errors associated with axis "variable"</doc>
	</field>
	<field name="data" type="NX_FLOAT[:...]|NX_INT[:...]">
		<!-- attributes
			signal="1" 
			axes="[...]" 
			long_name="{Title of data}"
		 -->
		 <doc>Data values</doc>
	</field>
	<field name="errors" type="NX_FLOAT[:...]">
		<doc>
			Standard deviations of data values - 
			the data array is identified by the attribute signal="1". 
			This array must have the same dimensions as the data
		</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXpolarizer.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXpolarizer" 
	type="group" extends="NXobject">
    <doc>Template of a beamline spin polarizer.
        
        This is a first cut. This is NOT the last word.</doc>
    <field name="type" type="NX_CHAR">
        <doc>crystal,supermirror</doc>
    </field>
    <field name="composition" type="NX_CHAR"/>
    <field name="reflection" type="NX_INT">
        <doc>[hkl] values of nominal reflection</doc>
        <dimensions>3</dimensions>
    </field>
    <field name="efficiency" type="NX_CHAR">
        <doc>polarizing efficiency</doc>
    </field>
</definition>
