=== Acidburn0zzz/definitions/base_classes/nxdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsd-documentation.xsl" ?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.nexusformat.org"
	xmlns:nx="http://www.nexusformat.org"
	elementFormDefault="qualified">
	
	<!-- define the document root element -->
	<xs:element name="definition" type="nx:definitionType" />

	<xs:complexType name="definitionType">
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded" />
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type" use="required" type="nx:definitionTypeAttr"/>
		<xs:attribute name="extends" use="required"/>
	</xs:complexType>

	<xs:simpleType name="definitionTypeAttr">
		<xs:restriction base="xs:string">
			<xs:enumeration value="group"/>
			<xs:enumeration value="definition"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="groupGroup">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="group" type="nx:groupType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field" type="nx:fieldType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="basicComponent">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="type" use="required" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:simpleType name="docType">
		<xs:annotation>
			<xs:documentation>
				This is the basic definition of a new type.
				Components must derive from an existing type 
				and optionally provide documentation.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:complexType name="groupType">
		<xs:annotation>
			<xs:documentation>
				A group element will be used to refer to an existing NX object or locally-defined component.
			</xs:documentation>
		</xs:annotation>
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" use="required"></xs:attribute>
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:annotation>
				<xs:documentation>
					A field element will be used to declare a new element in the component being defined.
    	       	</xs:documentation>
			</xs:annotation>
			<xs:extension base="nx:basicComponent">
				<xs:sequence>
					<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>
								A new element may expect or require some attributes.
    	    			   	</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="name" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== Acidburn0zzz/definitions/base_classes/NXlog.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXlog" 
    type="group" extends="NXobject">
    <doc>Definition of logged information, i.e. information monitored during the run. They contain
        the logged values and the times at which they were measured as elapsed time since a starting
        time recorded in ISO8601 format. This method of storing logged data helps to distinguish
        instances in which a variable is a dimension scale of the data, in which case it is stored
        in an NXdata group, and instances in which it is logged during the run, when it should be
        stored in an NXlog group.</doc>
	<field name="time" type="NX_FLOAT">
		<doc>
			Time of logged entry. The times are relative to the "start" attribute 
			and in the units specified in the "units" attribute.
        </doc>
        <attribute name="start" type="NX_DATE_TIME" />
	</field>
	<field name="value" units="NX_ANY" type="NX_NUMBER">
		<doc>Array of logged value, such as temperature</doc>
	</field>
	<field name="raw_value" units="NX_ANY" type="NX_NUMBER">
		<doc>Array of raw information, such as thermocouple voltage</doc>
	</field>
	<field name="description">
		<doc>Description of logged value</doc>
	</field>
	<field name="average_value" type="NX_FLOAT" units="NX_ANY">
	</field>
	<field name="average_value_error" type="NX_FLOAT" units="NX_ANY">
		<doc>standard deviation of average_value</doc>
	</field>
	<field name="minimum_value" type="NX_FLOAT" units="NX_ANY">
	</field>
	<field name="maximum_value" type="NX_FLOAT" units="NX_ANY">
	</field>
	<field name="duration" type="NX_FLOAT" units="NX_ANY">
		<doc>Total time log was taken</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXnote.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXnote" 
    type="group" extends="NXobject">
	<doc>This class can be used to store additional information in a 
		NeXus file e.g. pictures, movies, audio, additional text logs
	</doc>
	<field name="author">
		<doc>Author or creator of note</doc>
	</field>
	<field name="date" type="NX_DATE_TIME">
		<doc>Date note created/added</doc>
	</field>
	<field name="type">
		<doc>Mime content type of note data field e.g. image/jpeg, text/plain, text/html}</doc>
	</field>
	<field name="file_name">
		<doc>Name of original file name if note was read from an external source</doc>
	</field>
	<field name="description">
		<doc>Title of an image or other details of the note</doc>
	</field>
	<field name="data" type="NX_BINARY">
		<doc>Binary note data - if text, line terminator is [CR][LF].</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/contributed_definitions/NXarpes.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="nxdlformat.xsl" ?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008-2012 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition name="NXarpes" extends="NXobject" type="group"
    version="1.0"  category="application"
    xmlns="http://definition.nexusformat.org/nxdl/@NXDL_RELEASE@"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/@NXDL_RELEASE@ ../nxdl.xsd "
    svnid="$Id$">
    <doc>
	This is an application definition for angular resolved photo electron spectroscopy.
     	It has been drawn up with hemispherical electron analysers in mind. 
    </doc>
    <group type="NXentry">
        <attribute name="entry">
            <doc>NeXus convention is to use "entry1", "entry2", ... 
                for analysis software to locate each entry</doc>
        </attribute>
        <field name="title"/>
        <field name="start_time" type="NX_DATE_TIME"/>
        <field name="definition">
            <doc> Official NeXus NXDL schema to which this file conforms </doc>
            <enumeration>
                <item value="NXarpes"></item>
            </enumeration>
        </field>
        <group type="NXinstrument">
            <group type="NXsource">
                <field name="type"/>
                <field name="name"/>
                <field name="probe">
                    <enumeration>
                        <item value="x-ray"/>
                    </enumeration>
                </field>
            </group>
            <group type="NXmonochromator" name="monochromator">
              <field name="energy">
              </field>
            </group>
            <group type="NXdetector" name="analyser">
              <field name="data">
                <!-- <dimensions rank="1">
                  <dim index="1" value="np" />
                </dimensions> -->
                  <doc>mark this field with attribute  signal="1"</doc>
              </field>
              <field name="lens_mode">
		<doc>setting for the electron analyser lens</doc>
              </field>
              <field name="acquisition_mode">
                    <enumeration>
                        <item value="swept"/>
                        <item value="fixed"/>
                    </enumeration>
              </field>
              <field name="entrance_slit_shape">
                    <enumeration>
                        <item value="curved"/>
                        <item value="straight"/>
                    </enumeration>
              </field>
              <field name="entrance_slit_setting">
		<doc>dial setting of the entrance slit</doc>
              </field>
              <field name="entrance_slit_size" units="NX_LENGTH">
		<doc>size of the entrance slit</doc>
              </field>
              <field name="pass_energy" units="NX_ENERGY">
		<doc>energy of the electrons on the mean path of the analyser</doc>
              </field>
              <field name="number_of_sweeps">
              </field>
              <field name="time_per_channel" units="NX_TIME">
              </field>
              <field name="angles">
		<doc>angular axis of the analyser data</doc>
              </field>
              <field name="energies">
		<doc>energy axis of the analyser data</doc>
              </field>
            </group>
        </group>
        <group type="NXsample">
            <field name="name">
                <doc>Descriptive name of sample</doc>
            </field>
            <field name="temperature" units="NX_TEMPERATURE">
            </field>
        </group>
        <group type="NXdata">
        </group>
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXbending_magnet.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXbending_magnet" 
	type="group" extends="NXobject">

	<doc>description for a bending magnet</doc>
	<field name="critical_energy" type="NX_FLOAT" />
	<field name="bending_radius" type="NX_FLOAT" />
	<group type="NXdata"><doc>bending magnet spectrum</doc></group>
	<group type="NXgeometry"><doc>Engineering" position of bending magnet</doc></group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXmirror.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXmirror" 
	type="group" extends="NXobject">
    <doc>Template of a beamline supermirror.</doc>
    <group type="NXgeometry"/>
    <field name="description" type="NX_CHAR"/>
    <field name="incident_angle" type="NX_FLOAT"/>
    <group type="NXdata" name="reflectivity">
        <doc>Reflectivity as function of wavelength</doc>
    </group>
    <field name="bend_angle_x" type="NX_FLOAT"/>
    <field name="bend_angle_y" type="NX_FLOAT"/>
    <field name="interior_atmosphere" type="NX_CHAR">
        <enumeration>
            <item value="vacuum"/>
            <item value="helium"/>
            <item value="argon"/>
        </enumeration>
    </field>
    <field name="external_material" type="NX_CHAR">
        <doc>external material outside substrate</doc>
    </field>
    <field name="m_value" type="NX_FLOAT"/>
    <field name="substrate_material" type="NX_CHAR"/>
    <field name="substrate_thickness" type="NX_FLOAT"/>
    <field name="coating_material" type="NX_CHAR"/>
    <field name="substrate_roughness" type="NX_FLOAT"/>
    <field name="coating_roughness" type="NX_FLOAT"/>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXattenuator.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXattenuator" type="group" extends="NXobject">
    <doc>Template of a beamline attenuator.</doc>
    <field name="distance" type="NX_FLOAT" units="m">
        <doc>Distance from sample</doc>
    </field>
    <field name="type" type="NX_CHAR">
        <doc>Type of attenuator, e.g. polythene</doc>
    </field>
    <field name="thickness" type="NX_FLOAT" units="cm">
        <doc>Thickness of attenuator along beam direction</doc>
    </field>
    <field name="scattering_cross_section" type="NX_FLOAT" units="barns">
        <doc>Scattering cross section (coherent+incoherent)</doc>
    </field>
    <field name="absorption_cross_section" type="NX_FLOAT" units="barns">
        <doc>Absorption cross section</doc>
    </field>
    <field name="attenuator_transmission" type="NX_FLOAT">
        <doc>The nominal amount of the beam that gets through (transmitted intensity)/(incident
            intensity)</doc>
    </field>
</definition>

=== Acidburn0zzz/definitions/applications/NXdirecttof.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008-2010 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date: 2010-07-21 15:17:14 +0200 (Wed, 21 Jul 2010) $
# $Author: Mark Koennecke $
# $Revision: 567 $
# $HeadURL: https://svn.nexusformat.org/definitions/trunk/applications/NXtofraw.nxdl.xml $
# $Id: NXtofraw.nxdl.xml 567 2010-07-21 13:17:14Z Mark Koennecke $
########### SVN repository information ###################
-->
<definition name="NXdirecttof" extends="NXtofraw" type="group"
  category="application"
    xmlns="http://definition.nexusformat.org/nxdl/3.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
    version="1.0b"
    svnid="$Id: NXdirecttof.nxdl.xml 567 2010-07-21 13:17:14Z Mark Koennecke $">
    <doc>This is a application definition for raw data from a direct geometry TOF spectrometer</doc>
    <group type="NXentry" name="entry">
      <field name="title" />
      <field name="start_time" type="NX_DATE_TIME" />
      <field name="definition">
        <doc> Official NeXus NXDL schema to which this file conforms </doc>
        <enumeration>
          <item value="NXdirecttof"/>
        </enumeration>
      </field>
     <group type="NXinstrument">
       <group type="NXfermi_chopper" name="fermi_chopper">
        <field name="rotation_speed" type="NX_FLOAT" units="NX_FREQUENCY">
          <doc>chopper rotation speed</doc>
        </field>
       <field name="energy" type="NX_FLOAT" units="NX_ENERGY">
            <doc>energy selected</doc>
       </field> 
       </group>
     </group>  
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXshape.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXshape" 
	type="group" extends="NXobject">
	<doc>
		This is the description of the general shape and size of a 
		component, which may be made up of "numobj" separate 
		elements - it is used by the NXgeometry class
	</doc>
	<attribute name="name" type="NX_CHAR" />
	<field name="shape" type="NX_CHAR">
		<doc>"nxcylinder", "nxbox", "nxsphere", ...</doc>
	</field>
	<field name="size" type="NX_FLOAT" units="NX_LENGTH">
		<doc>
			physical extent of the object along its local axes (after NXorientation) 
			with the center of mass at the local origin (after NXtranslate).
			The meaning and location of these axes will vary according to the value 
			of the "shape" variable. nshapepar defines how many parameters. For the 
			"nxcylinder" type the paramters are (diameter,height). For the "nxbox" type 
			the parameters are (length,width,height). For the "nxsphere" type the 
			parameters are (diameter).
		</doc>
		<dimensions>[numobj,nshapepar]</dimensions>
	</field>
</definition>
