=== Acidburn0zzz/definitions/base_classes/nxdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsd-documentation.xsl" ?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.nexusformat.org"
	xmlns:nx="http://www.nexusformat.org"
	elementFormDefault="qualified">
	
	<!-- define the document root element -->
	<xs:element name="definition" type="nx:definitionType" />

	<xs:complexType name="definitionType">
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded" />
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type" use="required" type="nx:definitionTypeAttr"/>
		<xs:attribute name="extends" use="required"/>
	</xs:complexType>

	<xs:simpleType name="definitionTypeAttr">
		<xs:restriction base="xs:string">
			<xs:enumeration value="group"/>
			<xs:enumeration value="definition"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="groupGroup">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="group" type="nx:groupType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field" type="nx:fieldType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="basicComponent">
		<xs:sequence>
			<xs:element name="doc" type="nx:docType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="type" use="required" />
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:simpleType name="docType">
		<xs:annotation>
			<xs:documentation>
				This is the basic definition of a new type.
				Components must derive from an existing type 
				and optionally provide documentation.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
	<xs:complexType name="groupType">
		<xs:annotation>
			<xs:documentation>
				A group element will be used to refer to an existing NX object or locally-defined component.
			</xs:documentation>
		</xs:annotation>
		<xs:group ref="nx:groupGroup" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" use="required"></xs:attribute>
	</xs:complexType>

	<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

	<xs:complexType name="fieldType">
		<xs:complexContent>
			<xs:annotation>
				<xs:documentation>
					A field element will be used to declare a new element in the component being defined.
    	       	</xs:documentation>
			</xs:annotation>
			<xs:extension base="nx:basicComponent">
				<xs:sequence>
					<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>
								A new element may expect or require some attributes.
    	    			   	</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="name" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== Acidburn0zzz/definitions/base_classes/NXfermi_chopper.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXfermi_chopper" 
	type="group" extends="NXobject">
	<doc>Description of a Fermi chopper, possibly with curved slits.</doc>
	<field name="type">
		<doc>Fermi chopper type</doc>
	</field>
	<field name="rotation_speed" type="NX_FLOAT" units="NX_FREQUENCY">
		<doc>chopper rotation speed</doc>
	</field>
	<field name="radius" type="NX_FLOAT" units="NX_LENGTH">
		<doc>radius of chopper</doc>
	</field>
	<field name="slit" type="NX_FLOAT" units="NX_LENGTH">
		<doc>width of an individual slit</doc>
	</field>
	<field name="r_slit" type="NX_FLOAT" units="NX_LENGTH">
		<doc>radius of curvature of slits</doc>
	</field>
	<field name="num" type="NX_INT">
		<doc>number of slits</doc>
	</field>
	<field name="height" type="NX_FLOAT" units="NX_LENGTH">
		<doc>input beam height</doc>
	</field>
	<field name="width" type="NX_FLOAT" units="NX_LENGTH">
		<doc>input beam width</doc>
	</field>
	<field name="wavelength" type="NX_FLOAT">
		<!-- should have units of Angstroms or nm or pm -->
		<doc>Wavelength transmitted by chopper</doc>
	</field>
	<group type="NXgeometry">
		<doc>geometry of the fermi chopper</doc>
	</group>
	<field name="absorbing_material">
		<doc>absorbing material</doc>
	</field>
	<field name="transmitting_material">
		<doc>transmitting material</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXenvironment.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXenvironment" 
	type="group" extends="NXobject">
	<doc>This class describes an external condition applied to the sample</doc>
	<field name="name" type="NX_CHAR"><doc>Apparatus identification code/model number; e.g. OC100 011</doc></field>
	<field name="short_name" type="NX_CHAR"><doc>Alternative short name, perhaps for dashboard display like a present Seblock name</doc></field>
	<field name="type" type="NX_CHAR"><doc>Type of apparatus. This could be the SE codes in scheduling database; e.g. OC/100</doc></field>
	<field name="description" type="NX_CHAR"><doc>Description of the apparatus; e.g. 100mm bore orange cryostat with Roots pump</doc></field>
	<field name="program" type="NX_CHAR"><doc>Program controlling the apparatus; e.g. LabView VI name</doc></field>
	<group name="position" type="NXgeometry"><doc>The position and orientation of the apparatus</doc></group>
	<group type="NXnote"><doc>Additional information, LabView logs, digital photographs, etc</doc></group>
	<group type="NXsensor" />
</definition>

=== Acidburn0zzz/definitions/base_classes/NXuser.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXuser" 
	type="group" extends="NXobject">
	<doc>
		Template of user's contact information.  The format allows more 
		than one user with the same affiliation and contact information, 
		but a second NXuser group should be used if they have different 
		affiliations, etc.
	</doc>
	<field name="name">
		<doc>Name of user responsible for this entry</doc>
	</field>
	<field name="role">
		<doc>
			Role of user responsible for this entry.
			Suggested roles are "local_contact", 
			"principal_investigator", and "proposer"
		</doc>
	</field>
	<field name="affiliation">
		<doc>Affiliation of user</doc>
	</field>
	<field name="address">
		<doc>Address of user</doc>
	</field>
	<field name="telephone_number">
		<doc>Telephone number of user</doc>
	</field>
	<field name="fax_number">
		<doc>Fax number of user</doc>
	</field>
	<field name="email">
		<doc>Email of user</doc>
	</field>
	<field name="facility_user_id">
		<doc>
			facility based unique identifier for this person 
			e.g. their identification code on the facility 
			address/contact database
		</doc>
	</field>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXinstrument.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXinstrument" 
    type="group" extends="NXobject">
	<doc>
		Template of instrument descriptions comprising various beamline components. 
		Each component will also be a NeXus group defined by its distance from the 
		sample. Negative distances represent beamline components that are before the 
		sample while positive distances represent components that are after the sample. 
		This device allows the unique identification of beamline components in a way 
		that is valid for both reactor and pulsed instrumentation.
	</doc>
	<field name="name" type="NX_CHAR">
		<doc>Name of instrument</doc>
	</field>
	<group type="NXsource" />
	<group type="NXdisk_chopper" />
	<group type="NXfermi_chopper" />
	<group type="NXvelocity_selector" />
	<group type="NXguide" />
	<group type="NXcrystal" />
	<group type="NXaperture" />
	<group type="NXfilter" />
	<group type="NXcollimator" />
	<group type="NXattenuator" />
	<group type="NXpolarizer" />
	<group type="NXflipper" />
	<group type="NXmirror" />
	<group type="NXdetector" />
	<group type="NXbeam_stop" />
	<group type="NXcollimator" />
</definition>

=== Acidburn0zzz/definitions/base_classes/testing.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition  
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.nexusformat.org"
	xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd "
	
    name="NXfermi_chopper" 
    type="group" 
    extends="NXchopper">

    <group type="NXgeometry">
        <doc>geometry of the fermi chopper</doc>
    </group>
    <field name="type" type="NX_CHAR">
        <doc>fchopper type</doc>
    </field>
<!--    <bob flippy="123"/>-->
    <field name="radius" type="NX_LENGTH">
        <doc>radius of chopper</doc>
        <attribute name="colour" />
    </field>
</definition>

=== Acidburn0zzz/definitions/contributed_definitions/NXsai_controller.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="nxdlformat.xsl" ?>
<!--
# NXtechnical_data: candidate NeXus base class definition

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/nxdl/3.1" category="contributed"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
    name="NXsai_controller" version="1.0"
    svnid="$Id$" 
    type="group"
    extends="NXobject">

    <doc>(definition implied by usage) Subclass of NXinstrument used by Soleil. This class appears
        in the example data files provided from Soleil. This class should be considered as a base
        class (and relocated there, once approved by the NIAC). </doc>

    <!-- documentation taken from one of the Soleil example files -->
    <group type="NXtechnical_data" name="Frequency">
        <doc>DAQ board sampling frequency</doc>
    </group>
    <group type="NXtechnical_data" name="IntegrationTime">
        <doc>buffer integration time</doc>
    </group>
    <group type="NXtechnical_data" name="TriggerNumber">
        <doc>set to 0 at init, means that extern trigger mode disabled. if triggerNumber > 0, means
            extern trigger mode enabled. read part is the current trigger</doc>
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXcrystal.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# NeXus - Neutron and X-ray Common Data Format
# 
# Copyright (C) 2008 NeXus International Advisory Committee (NIAC)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# For further information, see http://www.nexusformat.org

########### SVN repository information ###################
# $Date$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################
-->
<definition xmlns="http://definition.nexusformat.org/nxdl/3.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
    name="NXcrystal" 
    svnid="$Id$"
    type="group" extends="NXobject">

    <doc>Template of a crystal monochromator or analyzer. Permits double bent
        monochromator comprised of multiple segments with anisotropic 
        Gaussian mosaic.
        
        If curvatures are set to zero or are absent, array 
        is considered to be flat.
        
        Scattering vector is perpendicular to surface. Crystal is oriented
        parallel to beam incident on crystal before rotation, and lies in
        vertical plane.</doc>
    <group type="NXgeometry">
        <doc>Position of crystal</doc>
    </group>
    <field name="type">
        <enumeration>
            <item value="PG"><doc>Highly Oriented Pyrolytic Graphite</doc></item>
            <item value="Ge"/>
            <item value="Si"/>
            <item value="Cu"/>
            <item value="Fe3Si"/>
            <item value="CoFe"/>
            <item value="Cu2MnAl"><doc>Heusler</doc></item>
            <item value="Multilayer"/>
        </enumeration>
    </field>
    <field name="cut_angle" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Cut angle of reflecting Bragg plane and plane of crystal surface</doc>
    </field>
    <field name="unit_cell_a" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Unit cell lattice parameter: length of side a</doc>
    </field>
    <field name="unit_cell_b" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Unit cell lattice parameter: length of side b</doc>
    </field>
    <field name="unit_cell_c" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Unit cell lattice parameter: length of side c</doc>
    </field>
    <field name="unit_cell_alpha" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Unit cell lattice parameter: angle alpha</doc>
    </field>
    <field name="unit_cell_beta" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Unit cell lattice parameter: angle beta</doc>
    </field>
    <field name="unit_cell_gamma" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Unit cell lattice parameter: angle gamma</doc>
    </field>
    <field name="unit_cell_volume" type="NX_FLOAT" units="NX_ATOMIC_VOLUME">
        <doc>Volume of the unit cell</doc>
    </field>
    <field name="orientation_matrix" type="NX_FLOAT">
        <doc>Orientation matrix of single crystal sample using Busing-Levy convention</doc>
        <dimensions>3,3</dimensions>
    </field>
    <field name="wavelength" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Optimum diffracted wavelength</doc>
        <dimensions>i</dimensions>
    </field>
    <field name="lattice_parameter" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Lattice parameter of the nominal reflection</doc>
    </field>
    <field name="scattering_vector" type="NX_FLOAT" units="NX_WAVENUMBER">
        <doc>Scattering vector, Q, of nominal reflection</doc>
    </field>
    <field name="reflection" type="NX_INT" units="NX_UNITLESS">
        <doc>Miller indices (hkl) values of nominal reflection</doc>
        <dimensions>3</dimensions>
    </field>
    <field name="segment_width" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Horizontal width of individual segment</doc>
    </field>
    <field name="segment_height" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Vertical height of individual segment</doc>
    </field>
    <field name="segment_thickness" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Thickness of individual segment</doc>
    </field>
    <field name="segment_gap" type="NX_FLOAT" units="NX_LENGTH">
        <doc>Typical gap between adjacent segments</doc>
    </field>
    <field name="segment_columns" type="NX_FLOAT" units="NX_LENGTH">
        <doc>number of segment columns in horizontal direction</doc>
    </field>
    <field name="segment_rows" type="NX_FLOAT" units="NX_LENGTH">
        <doc>number of segment rows in vertical direction</doc>
    </field>
    <field name="mosaic_horizontal" type="NX_FLOAT" units="NX_ANGLE">
        <doc>horizontal mosaic Full Width Half Maximum</doc>
    </field>
    <field name="mosaic_vertical" type="NX_FLOAT" units="NX_ANGLE">
        <doc>vertical mosaic Full Width Half Maximum</doc>
    </field>
    <field name="curvature_horizontal" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Horizontal curvature of focusing crystal</doc>
    </field>
    <field name="curvature_vertical" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Vertical curvature of focusing crystal</doc>
    </field>
    <field name="polar_angle" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Polar (scattering) angle at which crystal assembly is positioned</doc>
        <dimensions>i</dimensions>
    </field>
    <field name="azimuthal_angle" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Azimuthal angle at which crystal assembly is positioned</doc>
        <dimensions>i</dimensions>
    </field>
    <field name="bragg_angle" type="NX_FLOAT" units="NX_ANGLE">
        <doc>Bragg angle of nominal reflection</doc>
        <dimensions>i</dimensions>
    </field>
    <field name="temperature" type="NX_FLOAT" units="NX_TEMPERATURE">
        <doc>average/nominal crystal temperature</doc>
    </field>
    <group type="NXlog" name="temperature_log">
        <doc>log file of crystal temperature</doc>
    </group>
    <group type="NXdata" name="reflectivity">
        <doc>crystal reflectivity versus wavelength</doc>
    </group>
    <group type="NXdata" name="transmission">
        <doc>crystal transmission versus wavelength</doc>
    </group>
</definition>

=== Acidburn0zzz/definitions/base_classes/NXroot.nxdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    ########### SVN repository information ###################
    # $Date$
    # $Author$
    # $Revision$
    # $HeadURL$
    # $Id$
    ########### SVN repository information ###################
-->
<definition xmlns="http://www.nexusformat.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.nexusformat.org nxdl.xsd"
    name="NXroot" 
    type="group" extends="NXobject">
    <doc>Definition of the root NeXus group.</doc>
    <attribute name="file_name" type="NX_CHAR">
        <doc>File name of original NeXus file</doc>
    </attribute>
    <attribute name="file_update_time" type="NX_CHAR">
        <doc>Date and time of last file change at close</doc>
    </attribute>
    <attribute name="NeXus_version" type="NX_CHAR">
        <doc>Version of NeXus API used in writing the file</doc>
    </attribute>
    <attribute name="HDF_version" type="NX_CHAR">
        <doc>Version of NeXus API used in writing the file</doc>
    </attribute>
    <attribute name="HDF5_version" type="NX_CHAR">
        <doc>Version of NeXus API used in writing the file</doc>
    </attribute>
    <attribute name="creator" type="NX_CHAR">
        <doc>facility or program where file originated</doc>
    </attribute>
    <group type="NXentry" minOccurs="1" >
        <doc>entries</doc>
    </group>
</definition>
